[package]
name = "fsync"
version = "0.1.0"
edition = "2018"

[dependencies]
notify = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
ssh2 = "0.9"
chrono = "0.4"
log = "0.4"
env_logger = "0.9"
simplelog = "0.11"
